CREATE TABLE IF NOT EXISTS `ScheduleExecution` (
  `id`            BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `scheduleId`    BIGINT(20)   NOT NULL,
  `isoId`         BIGINT(20)   NOT NULL,
  `testwareIsoId` BIGINT(20)   NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_SCHEDULE_ISO_TESTWARE_ISO` (`scheduleId`, `isoId`, `testwareIsoId`),
  KEY `FK_SCHEDULE_EXECUTION_SCHEDULE` (`scheduleId`),
  CONSTRAINT `FK_SCHEDULE_EXECUTION_SCHEDULE` FOREIGN KEY (`scheduleId`) REFERENCES `Schedule` (`id`),
  KEY `FK_SCHEDULE_EXECUTION_ISO` (`isoId`),
  CONSTRAINT `FK_SCHEDULE_EXECUTION_ISO` FOREIGN KEY (`isoId`) REFERENCES `Iso` (`id`),
  KEY `FK_SCHEDULE_EXECUTION_TESTWAREISO` (`testwareIsoId`),
  CONSTRAINT `FK_SCHEDULE_EXECUTION_TESTWAREISO` FOREIGN KEY (`testwareIsoId`) REFERENCES `TestwareIso` (`id`)
);